// <auto-generated />
namespace FIT5032_Assignment_Portfolio_V1._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Alteruid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alteruid));
        
        string IMigrationMetadata.Id
        {
            get { return "202310230506557_Alteruid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
