// <auto-generated />
namespace FIT5032_Assignment_Portfolio_V1._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addratingclass1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addratingclass1));
        
        string IMigrationMetadata.Id
        {
            get { return "202310220547020_addratingclass1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
